const xlsx = require('xlsx');

const adminData = [
  ["System", "Base URL", "Category", "Method", "Endpoint", "Description"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Auth & Dashboard", "POST", "/api/admin/login", "Admin login"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Auth & Dashboard", "GET", "/api/admin/verify", "Verify admin JWT token"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Auth & Dashboard", "GET", "/api/admin/dashboard", "Get dashboard statistics"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Auth & Dashboard", "GET", "/api/admin/seed-shipping", "Seed initial shipping data"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Auth & Dashboard", "GET", "/api/admin/reports", "Get generic system reports"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "User Management", "GET", "/api/admin/users", "Get all users"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "User Management", "POST", "/api/admin/users", "Create a new user"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "User Management", "PUT", "/api/admin/users/:id", "Update user details"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "User Management", "DELETE", "/api/admin/users/:id", "Ban/Delete user"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Items", "GET", "/api/admin/items/options", "Get dropdown options for items"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Items", "GET", "/api/admin/items", "Get all items"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Items", "POST", "/api/admin/items", "Create a new item"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Items", "PUT", "/api/admin/items/:id", "Update item details"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Items", "DELETE", "/api/admin/items/:id", "Delete an item"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Categories", "GET", "/api/admin/categories", "Get all main categories"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Categories", "POST", "/api/admin/categories", "Create a category"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Categories", "PUT", "/api/admin/categories/:id", "Update a category"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Categories", "DELETE", "/api/admin/categories/:id", "Delete a category"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Subcategories", "GET", "/api/admin/subcategories", "Get all subcategories"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Subcategories", "POST", "/api/admin/subcategories", "Create a subcategory"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Subcategories", "PUT", "/api/admin/subcategories/:id", "Update a subcategory"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Subcategories", "DELETE", "/api/admin/subcategories/:id", "Delete a subcategory"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Item Types", "GET", "/api/admin/item-types", "Get all item types"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Item Types", "POST", "/api/admin/item-types", "Create an item type"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Item Types", "PUT", "/api/admin/item-types/:id", "Update an item type"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Item Types", "DELETE", "/api/admin/item-types/:id", "Delete an item type"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Orders & Transactions", "GET", "/api/admin/orders", "Get all platform orders"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Orders & Transactions", "PUT", "/api/admin/orders/:id", "Update order status"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Orders & Transactions", "DELETE", "/api/admin/orders/:id", "Delete an order"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Orders & Transactions", "GET", "/api/admin/transactions", "View all transactions"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Orders & Transactions", "GET", "/api/admin/withdrawal-requests", "View withdrawal requests"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Orders & Transactions", "PUT", "/api/admin/withdrawal-requests/:id", "Approve/Deny withdrawal request"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Orders & Transactions", "GET", "/api/admin/payout-methods", "View user payout methods"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Finance & Currencies", "GET", "/api/admin/payment-methods", "Get available payment gateways"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Finance & Currencies", "POST", "/api/admin/payment-methods", "Create a payment method"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Finance & Currencies", "PUT", "/api/admin/payment-methods/:id", "Update a payment method"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Finance & Currencies", "DELETE", "/api/admin/payment-methods/:id", "Delete a payment method"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Finance & Currencies", "GET", "/api/admin/currencies", "Get all currencies"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Finance & Currencies", "POST", "/api/admin/currencies", "Add a new currency"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Finance & Currencies", "PUT", "/api/admin/currencies/:id", "Update currency"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Finance & Currencies", "DELETE", "/api/admin/currencies/:id", "Delete currency"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Localization", "GET", "/api/admin/languages", "Get all languages"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Localization", "POST", "/api/admin/languages", "Add a language"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Localization", "PUT", "/api/admin/languages/:id", "Update a language"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Localization", "DELETE", "/api/admin/languages/:id", "Delete a language"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Localization", "GET", "/api/timezones", "Fetch available timezones"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Notifications & Newsletter", "GET", "/api/admin/notifications", "Get admin notifications"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Notifications & Newsletter", "GET", "/api/admin/notifications/count", "Get unread count"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Notifications & Newsletter", "PUT", "/api/admin/notifications/read-all", "Mark all read"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Notifications & Newsletter", "PUT", "/api/admin/notifications/:id/read", "Mark specific read"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Notifications & Newsletter", "GET", "/api/admin/newsletter", "Get subscriber list"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Notifications & Newsletter", "PATCH", "/api/admin/newsletter/:id", "Update subscriber status"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Notifications & Newsletter", "DELETE", "/api/admin/newsletter/:id", "Remove subscriber"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System Settings", "GET", "/api/settings/types", "Get available setting categories"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System Settings", "GET", "/api/settings/:type", "Get settings for a specific type"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System Settings", "PUT", "/api/settings/:type", "Update settings by type"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System Settings", "GET", "/api/settings/db/backup", "Trigger database backup"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System Settings", "GET", "/api/settings/db/restore", "Trigger database restore"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System Settings", "POST", "/api/settings/db/backup", "Trigger database backup"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System Settings", "POST", "/api/settings/db/restore", "Trigger database restore"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System Settings", "GET", "/api/settings/db/mail_check", "Test SMTP settings"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "CMS Pages", "GET", "/api/pages", "Get all static pages"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "CMS Pages", "GET", "/api/pages/:slug", "Get page by URL slug"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "CMS Pages", "GET", "/api/pages/id/:id", "Get page by DB ID"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "CMS Pages", "POST", "/api/pages", "Create a new page"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "CMS Pages", "PUT", "/api/pages/:id", "Update a page"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "CMS Pages", "DELETE", "/api/pages/:id", "Delete a page"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Frontend CMS Content", "GET", "/api/frontend-content/:lang", "Get localized content"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Frontend CMS Content", "GET", "/api/frontend-content/admin/all", "Get all content blocks"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Frontend CMS Content", "PUT", "/api/frontend-content/admin/update", "Update specific block"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Frontend CMS Content", "PUT", "/api/frontend-content/admin/bulk-update", "Update multiple blocks"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Frontend CMS Content", "POST", "/api/frontend-content/admin/upload-image", "Upload image for CMS block"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Messages & Contact", "GET", "/api/admin-messages/conversations", "Get support tickets"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Messages & Contact", "GET", "/api/admin-messages/count", "Get unread message count"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Messages & Contact", "GET", "/api/admin-messages/:id", "Get ticket thread"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Messages & Contact", "POST", "/api/admin-messages", "Reply to a ticket"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Messages & Contact", "GET", "/api/contact", "Get all Contact Us submissions"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Messages & Contact", "PUT", "/api/contact/:id", "Update submission status"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Messages & Contact", "DELETE", "/api/contact/:id", "Delete submission"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Shipping Companies", "GET", "/api/shipping-companies", "Get all couriers"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Shipping Companies", "GET", "/api/shipping-companies/:id", "Get courier by ID"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Shipping Companies", "POST", "/api/shipping-companies", "Add courier"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Shipping Companies", "PUT", "/api/shipping-companies/:id", "Update courier"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Shipping Companies", "DELETE", "/api/shipping-companies/:id", "Delete courier"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Moderation Reports", "GET", "/api/moderation-reports", "Get user-reported items/profiles"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Moderation Reports", "PUT", "/api/moderation-reports/:id/status", "Update report status"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Moderation Reports", "POST", "/api/moderation-reports/:id/action", "Execute action on report"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Reports", "GET", "/api/reports", "Get general analytics reports"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Reports", "PUT", "/api/reports/:id/status", "Update general report status"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "Reports", "POST", "/api/reports/:id/action", "Handle general report action"],
  ["Admin Backend", "https://adminvinted.sangvish.com", "System", "GET", "/api/system/health", "Check system health"]
];

const vintedData = [
  ["System", "Base URL", "Category", "Method", "Endpoint", "Description"],
  ["Main Backend", "https://vinted.sangvish.com", "Global Settings", "GET", "/api/settings", "Merges all settings for frontend"],
  ["Main Backend", "https://vinted.sangvish.com", "Global Settings", "GET", "/api/settings/types", "Get available setting types"],
  ["Main Backend", "https://vinted.sangvish.com", "Global Settings", "GET", "/api/settings/:type", "Get settings by a specific type"],
  ["Main Backend", "https://vinted.sangvish.com", "Global Settings", "PUT", "/api/settings/:type", "Update settings by type"],
  ["Main Backend", "https://vinted.sangvish.com", "Global Settings", "GET", "/api/settings/db/mail_check", "Test SMTP connection"],
  ["Main Backend", "https://vinted.sangvish.com", "Global Settings", "GET", "/api/timezones", "Get available timezones"],
  ["Main Backend", "https://vinted.sangvish.com", "CMS Pages", "GET", "/api/pages", "Get all static pages"],
  ["Main Backend", "https://vinted.sangvish.com", "CMS Pages", "GET", "/api/pages/:slug", "Get page by URL slug"],
  ["Main Backend", "https://vinted.sangvish.com", "CMS Pages", "GET", "/api/pages/id/:id", "Get page by DB ID"],
  ["Main Backend", "https://vinted.sangvish.com", "CMS Pages", "POST", "/api/pages", "Create page"],
  ["Main Backend", "https://vinted.sangvish.com", "CMS Pages", "PUT", "/api/pages/:id", "Update page"],
  ["Main Backend", "https://vinted.sangvish.com", "CMS Pages", "DELETE", "/api/pages/:id", "Delete page"],
  ["Main Backend", "https://vinted.sangvish.com", "CMS Pages", "GET", "/api/frontend-content/:lang", "Get frontend content by language"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "POST", "/api/users", "Register a new user"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "POST", "/api/users/login", "Login user"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "POST", "/api/users/forgotpassword", "Request password reset"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "POST", "/api/users/send-signup-otp", "Send signup OTP"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "POST", "/api/users/verify-otp", "Verify the signup OTP"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "PUT", "/api/users/resetpassword/:resettoken", "Reset password"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "GET", "/api/users/me", "Get current logged-in user data"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "GET", "/api/users/profile", "Get current logged-in user profile"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "GET", "/api/users", "Get all users"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "GET", "/api/users/check-username/:username", "Check username existence"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "GET", "/api/users/:id/public", "Get public profile details"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "PUT", "/api/users/profile", "Update user profile"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "PATCH", "/api/users/ping", "Ping user online activity"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "PATCH", "/api/users/cookie-consent", "Update user cookie consent"],
  ["Main Backend", "https://vinted.sangvish.com", "Users & Authentication", "DELETE", "/api/users/delete", "Delete user account"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "GET", "/api/items", "Get a paginated list of items"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "POST", "/api/items", "Create a new item"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "GET", "/api/items/myitems", "Get my items"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "GET", "/api/items/:id", "Get details of an item"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "PUT", "/api/items/:id", "Update an item"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "DELETE", "/api/items/:id", "Delete an item"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "GET", "/api/items/:id/similar", "Get similar items"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "PUT", "/api/items/:id/discount", "Apply a discount"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "DELETE", "/api/items/:id/discount", "Remove a discount"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "GET", "/api/categories", "Fetch all main categories"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "POST", "/api/search/image", "Search items by image"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "GET", "/api/search/history", "Get user search history"],
  ["Main Backend", "https://vinted.sangvish.com", "Items & Categories", "POST", "/api/search/history", "Save query to search history"],
  ["Main Backend", "https://vinted.sangvish.com", "Favorites", "GET", "/api/favorites", "Get user favorite items"],
  ["Main Backend", "https://vinted.sangvish.com", "Favorites", "POST", "/api/favorites/:itemId", "Add/Remove an item from favorites"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "POST", "/api/orders", "Create a new order (checkout)"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "GET", "/api/orders", "Get all user orders"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "PUT", "/api/orders/:id/address", "Update shipping address for order"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "PUT", "/api/orders/:id/status", "Update order status"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "POST", "/api/orders/:id/cancel", "Cancel order"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "POST", "/api/orders/:id/return", "Request a return"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "POST", "/api/orders/:id/process-return", "Process return"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "GET", "/api/payments/methods", "Get available payment methods"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "POST", "/api/payments/stripe/create-intent", "Create Stripe Payment Intent"],
  ["Main Backend", "https://vinted.sangvish.com", "Orders & Payments", "POST", "/api/payments/webhook", "Stripe Webhook listener"],
  ["Main Backend", "https://vinted.sangvish.com", "Wallet & Payouts", "GET", "/api/wallet/me", "Get wallet balance"],
  ["Main Backend", "https://vinted.sangvish.com", "Wallet & Payouts", "POST", "/api/wallet/withdraw", "Request a withdrawal"],
  ["Main Backend", "https://vinted.sangvish.com", "Wallet & Payouts", "GET", "/api/wallet/withdrawals", "Get withdrawal history"],
  ["Main Backend", "https://vinted.sangvish.com", "Wallet & Payouts", "GET", "/api/wallet/payout-methods", "Get saved payout methods"],
  ["Main Backend", "https://vinted.sangvish.com", "Wallet & Payouts", "POST", "/api/wallet/payout-methods", "Add payout method"],
  ["Main Backend", "https://vinted.sangvish.com", "Wallet & Payouts", "PUT", "/api/wallet/payout-methods/:id", "Update payout method"],
  ["Main Backend", "https://vinted.sangvish.com", "Wallet & Payouts", "DELETE", "/api/wallet/payout-methods/:id", "Delete payout method"],
  ["Main Backend", "https://vinted.sangvish.com", "Wallet & Payouts", "PUT", "/api/wallet/payout-methods/:id/default", "Set as default payout method"],
  ["Main Backend", "https://vinted.sangvish.com", "Shipping", "GET", "/api/shipping/companies", "Get active shipping companies"],
  ["Main Backend", "https://vinted.sangvish.com", "Shipping", "PUT", "/api/shipping/dispatch/:id", "Mark order as dispatched"],
  ["Main Backend", "https://vinted.sangvish.com", "Shipping", "PUT", "/api/shipping/status/:id", "Update courier tracking status"],
  ["Main Backend", "https://vinted.sangvish.com", "Shipping", "GET", "/api/shipping-companies", "Fetch carrier list"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "GET", "/api/messages/conversations", "Get user conversations"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "GET", "/api/messages/:id", "Get messages in a conversation"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "POST", "/api/messages", "Send a new message"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "PATCH", "/api/messages/respond/:id", "Respond to a request"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "PATCH", "/api/messages/block/:id", "Block the user"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "PATCH", "/api/messages/offer/:id", "Respond to a price offer"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "GET", "/api/admin-messages/count", "Get unread admin messages"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "GET", "/api/admin-messages/conversations", "Get conversations with support"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "GET", "/api/admin-messages/:id", "Get support messages"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "POST", "/api/admin-messages", "Send message to support"],
  ["Main Backend", "https://vinted.sangvish.com", "Messages", "PATCH", "/api/admin-messages/respond/:id", "Respond to support request"],
  ["Main Backend", "https://vinted.sangvish.com", "Reviews", "POST", "/api/reviews", "Create a review"],
  ["Main Backend", "https://vinted.sangvish.com", "Reviews", "GET", "/api/reviews/user/:userId", "Get reviews for user"],
  ["Main Backend", "https://vinted.sangvish.com", "Reviews", "GET", "/api/reviews/order/:orderId", "Get review for an order"],
  ["Main Backend", "https://vinted.sangvish.com", "Notifications", "GET", "/api/notifications", "Get all alerts"],
  ["Main Backend", "https://vinted.sangvish.com", "Notifications", "PATCH", "/api/notifications/read-all", "Mark all as read"],
  ["Main Backend", "https://vinted.sangvish.com", "Notifications", "PATCH", "/api/notifications/:id/read", "Mark single as read"],
  ["Main Backend", "https://vinted.sangvish.com", "Notifications", "DELETE", "/api/notifications/:id", "Delete alert"],
  ["Main Backend", "https://vinted.sangvish.com", "Notifications", "POST", "/api/newsletter/subscribe", "Subscribe to newsletter"],
  ["Main Backend", "https://vinted.sangvish.com", "Notifications", "POST", "/api/contact", "Submit contact us message"],
  ["Main Backend", "https://vinted.sangvish.com", "Localization", "GET", "/api/currencies", "Fetch available currencies"],
  ["Main Backend", "https://vinted.sangvish.com", "Localization", "GET", "/api/languages", "Fetch available languages"],
  ["Main Backend", "https://vinted.sangvish.com", "Moderation", "POST", "/api/reports", "Submit a report"]
];

const wb = xlsx.utils.book_new();
const wsAdmin = xlsx.utils.aoa_to_sheet(adminData);
const wsVinted = xlsx.utils.aoa_to_sheet(vintedData);

xlsx.utils.book_append_sheet(wb, wsAdmin, "Admin API Keys");
xlsx.utils.book_append_sheet(wb, wsVinted, "Vinted API Keys");

xlsx.writeFile(wb, "../vinted_api_keys_list.xlsx");
console.log("Excel file generated successfully!");
